#!/bin/bash
. /tmp/antivirus.properties

wget=/usr/bin/wget
working_dir="/root/"
wget_opts='-O '
echo $virus_db
echo $whitelist_db

cd $working_dir
$wget $wget_opts $virus_file_name $virus_db
$wget $wget_opts $whitelist_file_name $whitelist_db
